option(BUILD_WITH_GFLAGS "Build with gflags" ON)
option(BUILD_WITH_GLOG "Build with glog" ON)

if (BUILD_WITH_GFLAGS)
    set(GFLAGS_BUILD_SHARED_LIBS OFF CACHE BOOL "Description of my option")
    # set(GFLAGS_BUILD_gflags_LIB OFF CACHE BOOL "Description of my option")
    include_directories(${CMAKE_BINARY_DIR}/3rd-party/gflags/include)
    add_subdirectory(${CMAKE_SOURCE_DIR}/3rd-party/gflags)
endif(BUILD_WITH_GFLAGS)

if (BUILD_WITH_GLOG)
    set(BUILD_SHARED_LIBS OFF CACHE BOOL "Description of my option")
    set(BUILD_EXAMPLES OFF CACHE BOOL "Description of my option")
    set(WITH_GFLAGS OFF CACHE BOOL "Description of my option")
    set(WITH_GTEST OFF CACHE BOOL "Description of my option")
    set(BUILD_TESTING OFF CACHE BOOL "Description of my option")
    include_directories(${CMAKE_SOURCE_DIR}/3rd-party/glog/src)
    add_subdirectory(${CMAKE_SOURCE_DIR}/3rd-party/glog)
endif(BUILD_WITH_GLOG)
